output-format: grouped
inherits:
  - full_pep8
  - strictness_low
pylint:
  disable:
    # This check (for missing method arguments) is broken in latest pylint:
    #
    #     https://bitbucket.org/logilab/pylint/issue/205
    - E1120
    # This check (for inherited objects to be classes) is broken in pylint 1.4
    # for zope.interface.Interface.
    - E0239
pep8:
  options:
    max-line-length: 79
ignore-paths:
  - h/_version.py
  - h/migrations/
  - versioneer.py
