language:
  - python
python:
  - '2.7'
before_install:
  - sudo /usr/share/elasticsearch/bin/plugin -install elasticsearch/elasticsearch-analysis-icu/2.4.1
  - sudo service elasticsearch restart
install:
  - gem install sass
  - gem install compass
  - pip install prospector
  - make
services:
  - elasticsearch
script:
  - make test
  - make lint
  - hypothesis-buildext development.ini chrome --base http://localhost
  - hypothesis-buildext production.ini chrome --base https://hypothes.is --assets chrome-extension://notarealkey/public
  - hypothesis-buildext development.ini firefox --base http://localhost
  - hypothesis-buildext production.ini firefox --base https://hypothes.is --assets resource://notarealkey/hypothesis/data
notifications:
  irc:
    channels:
       "chat.freenode.net#hypothes.is"
    on_success: "change"
    on_failure: "always"
