language:
  - python
python:
  - '2.7'
before_install:
  - sudo /usr/share/elasticsearch/bin/plugin -install elasticsearch/elasticsearch-analysis-icu/2.3.0
  - sudo service elasticsearch restart
install:
  - gem install sass
  - gem install compass
  - pip install prospector
  - make
services:
  - elasticsearch
script:
  - make test
  - prospector -P .prospector.yaml h
  - hypothesis extension development.ini chrome http://localhost
  - hypothesis extension production.ini chrome https://hypothes.is chrome-extension://notarealkey/public
  - hypothesis extension development.ini firefox http://localhost
  - hypothesis extension production.ini firefox https://hypothes.is resource://notarealkey/hypothesis/data
notifications:
  irc:
    channels:
       "chat.freenode.net#hypothes.is"
    on_success: "change"
    on_failure: "always"
