language:
  - python
python:
  - '2.7'
install:
  # Install temporarily pinned to avoid a regression in sass==3.4.6
  #
  #   https://github.com/sass/sass/issues/1476
  - gem install sass:3.4.5
  - gem install compass
  - pip install prospector
  - make
services:
  - elasticsearch
script:
  - make test
  - prospector -P .prospector.yaml h
  - hypothesis extension development.ini chrome http://localhost
  - hypothesis extension development.ini firefox http://localhost
notifications:
  irc:
    channels:
       "chat.freenode.net#hypothes.is"
    on_success: "change"
    on_failure: "always"
