language:
  - python
python:
  - '2.7'
install:
  - gem install sass
  - gem install compass
  - make
services:
  - elasticsearch
script:
  - make test
notifications:
  irc:
    channels:
       "chat.freenode.net#hypothes.is"
    on_success: "change"
    on_failure: "always"
