language:
  - python
python:
  - '2.7'
install:
  - gem install sass
  - gem install compass
  - npm install -g coffee-script
  - pip install -r requirements.txt
services:
  - elasticsearch
before_script:
  - curl https://gist.github.com/santiycr/5139565/raw/sauce_connect_setup.sh | bash
script:
  - make test
after_failure:
  - cat /tmp/gunicorn.error.log
addons:
  sauce_connect:
    username: hypothesiseng
    access_key:
      secure: pFqnZRSOVe9R3QsB/w7iYwQaGGSZ1g2c6554lHD/t2NbUKfRwrHRyNcANKcnIpiVu73FvWmHJH8SB7Mycnd3MrR80+oyUdC42Me9DmB5k8pYtpl9xPTC4P28oPe5bgyTKTgxoMoERzdJoSCjINZsEvtnmFNxfpAWRUIa5N1mE84=
notifications:
  irc:
    channels:
       "chat.freenode.net#hypothes.is"
    on_success: "change"
    on_failure: "always"
