language:
- python
python:
- '2.7'
install:
- sudo add-apt-repository --yes ppa:chris-lea/node.js
- sudo apt-get update --yes
- sudo apt-get install --yes nodejs
- sudo npm install -g coffee-script
- pip install -r requirements.txt
- gem install compass
services:
- elasticsearch
before_script:
- curl https://gist.github.com/santiycr/5139565/raw/sauce_connect_setup.sh | bash
script:
- make test
env:
  global:
  - secure: iOqIzaawOalSidKGRstfhiaZ9HykF+EEriG2cq6a/UGS65pguYyCogtkjFODG1cWlRh2cAICxeM6WOw4TWL9SFyb8sjfx6k2nAFOFuF3efNwuVaPkSS5zZfGAdLJmnGNivm0EdUBB17gl+P8QkiI1oQvYH2dsmF/VlhpHyGuoNk=
  - secure: Aw2SFoqCnLc5sfRxiD5nEzmPHomPWTzlnPG525fQxKUhigpvjcqI9C6elxgb7DnIQzQ9+WBjh0wdzuUYpLP/AnWk/vheKnx2+vj4ZuD4TxOG9hSog8mqpNcrpSuTgXf2S+bt5RH4l73TlhCU/3GEhEo5I0JWanHzvCefUrtRu14=
after_failure:
- cat pyramid.log
