# use Travis container build infrastructure
sudo: false
matrix:
  include:
    # Python (backend) tests
    - env: ACTION=tox
      language: python
      python: '2.7'
      addons:
        postgresql: "9.4"
      install: pip install tox
      before_script: createdb htest
      script: tox
      after_success:
        tox -e coverage
        tox -e codecov

    # Test web application frontend
    - env: ACTION=gulp
      language: node_js
      node_js: '4.3'
      before_install: npm install gulp-cli
      script: gulp test
cache:
  directories:
    - node_modules
    - $HOME/.cache/pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
notifications:
  slack:
    rooms:
      - secure: SKPwtfoH32aDop6hLhQdgrUhl58gM6CMBUATMdq0KMmEwCxskPbIArqxGUKxeeiO3c3jBQ+Yuq3b4m8GbR2AJxxelO0DRLNyV1lAjfeJ/QzCc3Taxqo0yel4uAFNg/oCYWH50dv2oAgDP3CHk/tKXmsgDWOjcm6A6k35xst16xI=
    on_success: change
    on_failure: always
